"use client";

import { useEffect, useRef } from "react";

declare global {
    interface Window { adsbygoogle: unknown[]; }
}

type AdType = "display" | "multiplex" | "in-article" | "in-feed";

interface AdBannerProps {
    type: AdType;
    slot: string;
    className?: string;
    /** display only — width hint for the container */
    format?: "auto" | "horizontal" | "rectangle" | "vertical";
    /** in-feed only — generated by AdSense when you created the unit */
    layoutKey?: string;
}

const AD_CLIENT = process.env.NEXT_PUBLIC_GOOGLE_AD_CLIENT ?? "";

function getInsProps(type: AdType, slot: string, format: string, layoutKey?: string) {
    switch (type) {
        case "multiplex":
            return {
                "data-ad-client": AD_CLIENT,
                "data-ad-slot": slot,
                "data-ad-format": "autorelaxed",
            };
        case "in-article":
            return {
                "data-ad-client": AD_CLIENT,
                "data-ad-slot": slot,
                "data-ad-layout": "in-article",
                "data-ad-format": "fluid",
            };
        case "in-feed":
            return {
                "data-ad-client": AD_CLIENT,
                "data-ad-slot": slot,
                "data-ad-format": "fluid",
                ...(layoutKey ? { "data-ad-layout-key": layoutKey } : {}),
            };
        default: // display
            return {
                "data-ad-client": AD_CLIENT,
                "data-ad-slot": slot,
                "data-ad-format": format,
                "data-full-width-responsive": "true",
            };
    }
}

export default function AdBanner({
    type,
    slot,
    className = "",
    format = "auto",
    layoutKey,
}: AdBannerProps) {
    const pushed = useRef(false);

    useEffect(() => {
        if (pushed.current || !AD_CLIENT || !slot) return;
        try {
            pushed.current = true;
            (window.adsbygoogle = window.adsbygoogle || []).push({});
        } catch {
            // script not loaded yet
        }
    }, [slot]);

    if (!AD_CLIENT || !slot) return null;

    const insProps = getInsProps(type, slot, format, layoutKey);
    const isMultiplex = type === "multiplex";

    return (
        <div
            className={`w-full overflow-hidden ${isMultiplex ? "my-2" : ""} ${className}`}
            aria-label="Advertisement"
        >
            <ins
                className="adsbygoogle"
                style={{ display: "block", textAlign: isMultiplex ? undefined : "center" }}
                {...insProps}
            />
        </div>
    );
}
